version: "3.8"
services:
  backend:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://KeithNPC:psql@db:5432/
    command: bash -c "npm run migrate && npm run start"
    ports:
      - 4000:4000
    env_file:
      - ./.env.local
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGUSER=KeithNPC
      - POSTGRES_USER=KeithNPC
      - POSTGRES_PASSWORD=psql
      - POSGRES_DB=spark
    volumes:
      - ./data:/var/lib/postgresql/data
    # https://stackoverflow.com/questions/65115627/safe-ways-to-specify-postgres-parameters-for-healthchecks-in-docker-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
